; RUN: llc --global-isel --mtriple=aarch64-- --stop-after=irtranslator -o - %s | FileCheck %s

define void @test_strict_fcmp(float %a, float %b) strictfp {
  %r0 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"oeq", metadata !"fpexcept.strict")
  %r1 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"ogt", metadata !"fpexcept.strict")
  %r2 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"oge", metadata !"fpexcept.strict")
  %r3 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"olt", metadata !"fpexcept.strict")
  %r4 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"ole", metadata !"fpexcept.strict")
  %r5 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"one", metadata !"fpexcept.strict")
  %r6 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"ord", metadata !"fpexcept.strict")
  %r7 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"uno", metadata !"fpexcept.strict")
  %r8 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"ueq", metadata !"fpexcept.strict")
  %r9 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"ugt", metadata !"fpexcept.strict")
  %r10 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"uge", metadata !"fpexcept.strict")
  %r11 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"ult", metadata !"fpexcept.strict")
  %r12 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"ule", metadata !"fpexcept.strict")
  %r13 = call i1 @llvm.experimental.constrained.fcmp.f32(float %a, float %b, metadata !"une", metadata !"fpexcept.strict")
  ret void
; CHECK: G_STRICT_FCMP floatpred(oeq)
; CHECK: G_STRICT_FCMP floatpred(ogt)
; CHECK: G_STRICT_FCMP floatpred(oge)
; CHECK: G_STRICT_FCMP floatpred(olt)
; CHECK: G_STRICT_FCMP floatpred(ole)
; CHECK: G_STRICT_FCMP floatpred(one)
; CHECK: G_STRICT_FCMP floatpred(ord)
; CHECK: G_STRICT_FCMP floatpred(uno)
; CHECK: G_STRICT_FCMP floatpred(ueq)
; CHECK: G_STRICT_FCMP floatpred(ugt)
; CHECK: G_STRICT_FCMP floatpred(uge)
; CHECK: G_STRICT_FCMP floatpred(ult)
; CHECK: G_STRICT_FCMP floatpred(ule)
; CHECK: G_STRICT_FCMP floatpred(une)
}

define void @test_strict_fcmps(float %a, float %b) strictfp {
  %r0 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"oeq", metadata !"fpexcept.strict")
  %r1 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"ogt", metadata !"fpexcept.strict")
  %r2 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"oge", metadata !"fpexcept.strict")
  %r3 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"olt", metadata !"fpexcept.strict")
  %r4 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"ole", metadata !"fpexcept.strict")
  %r5 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"one", metadata !"fpexcept.strict")
  %r6 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"ord", metadata !"fpexcept.strict")
  %r7 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"uno", metadata !"fpexcept.strict")
  %r8 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"ueq", metadata !"fpexcept.strict")
  %r9 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"ugt", metadata !"fpexcept.strict")
  %r10 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"uge", metadata !"fpexcept.strict")
  %r11 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"ult", metadata !"fpexcept.strict")
  %r12 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"ule", metadata !"fpexcept.strict")
  %r13 = call i1 @llvm.experimental.constrained.fcmps.f32(float %a, float %b, metadata !"une", metadata !"fpexcept.strict")
  ret void
; CHECK: G_STRICT_FCMPS floatpred(oeq)
; CHECK: G_STRICT_FCMPS floatpred(ogt)
; CHECK: G_STRICT_FCMPS floatpred(oge)
; CHECK: G_STRICT_FCMPS floatpred(olt)
; CHECK: G_STRICT_FCMPS floatpred(ole)
; CHECK: G_STRICT_FCMPS floatpred(one)
; CHECK: G_STRICT_FCMPS floatpred(ord)
; CHECK: G_STRICT_FCMPS floatpred(uno)
; CHECK: G_STRICT_FCMPS floatpred(ueq)
; CHECK: G_STRICT_FCMPS floatpred(ugt)
; CHECK: G_STRICT_FCMPS floatpred(uge)
; CHECK: G_STRICT_FCMPS floatpred(ult)
; CHECK: G_STRICT_FCMPS floatpred(ule)
; CHECK: G_STRICT_FCMPS floatpred(une)
}
